name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-main:
    name: Build All Except macOS ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache: true
      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
      - name: Sync Go Modules
        run: go mod vendor
      - name: Run GoReleaser build
        run: goreleaser build --clean --id=tikwm-linux-amd64 --id=tikwm-linux-arm64 --id=tikwm-windows-amd64 --id=tikwm-windows-arm64 --id=tikwm-darwin-amd64
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-main
          path: dist

  build-mac-arm:
    name: Build for macOS ARM64
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache: true
      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
      - name: Sync Go Modules
        run: go mod vendor
      - name: Run GoReleaser build
        run: goreleaser build --clean --id=tikwm-darwin-arm64
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-mac-arm
          path: dist

  release:
    name: Publish Release
    needs: [build-main, build-mac-arm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Download all dist artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Sync Go Modules
        run: go mod vendor
      - name: Run GoReleaser publisher
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --skip-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
